version: '3'
services:

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=QCb3OXlaXyrRhzNygiMhOauWS5kT7d96
      - POSTGRES_USER=apihhru_user
      - POSTGRES_DB=apihhru

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=apihhru_user
      - DB_PASSWORD=QCb3OXlaXyrRhzNygiMhOauWS5kT7d96
      - DB_HOST=chlmre64dadfmsgj44mg
      - DB_NAME=apihhru
      - POOL_MODE=transaction

    ports:
      - "5432:5432"
    depends_on:
      - db

volumes:
  pg_data: